"""Build a single-file, dependency-free HTML dashboard."""
from pathlib import Path
import json
from analysis import load_sales, kpis, grouped_profitability, monthly_profitability

ROOT = Path(__file__).resolve().parents[1]
df = load_sales(ROOT / "data/raw/retail_store_sales.xlsx")
records = df.fillna("").to_dict(orient="records")
summary = {
    "kpis": kpis(df),
    "category": grouped_profitability(df, "Categoria do Produto").to_dict(orient="records"),
    "subcategory": grouped_profitability(df, "Sub-Categoria do Produto").to_dict(orient="records"),
    "shipping": grouped_profitability(df, "Forma de Envio").to_dict(orient="records"),
    "region": grouped_profitability(df, "Região").to_dict(orient="records"),
    "segment": grouped_profitability(df, "Segmento do Cliente").to_dict(orient="records"),
    "monthly": monthly_profitability(df).assign(**{"Data da Venda": lambda x: x["Data da Venda"].dt.strftime("%Y-%m-%d")}).to_dict(orient="records"),
}
html = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bella Stationery | Profitability Decision Dashboard</title><style>
:root{--bg:#0b1020;--panel:#121a2d;--line:#263553;--text:#e9efff;--muted:#9eacc9;--cyan:#5ee7f7;--pink:#ff78b6;--green:#6ee7a8;--red:#ff7f91}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#090d19,#111b32);color:var(--text);font:14px system-ui,Segoe UI,sans-serif}header{padding:26px 5%;display:flex;gap:18px;align-items:center;border-bottom:1px solid var(--line)}header img{width:58px;height:58px;object-fit:contain}h1{font-size:25px;margin:0}h2{font-size:17px;margin:0 0 15px}.by{color:var(--cyan);margin-top:3px}.wrap{max-width:1500px;margin:auto;padding:24px 5%}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.panel{background:rgba(18,26,45,.94);border:1px solid var(--line);border-radius:14px;padding:17px;box-shadow:0 8px 25px #0003}.label{color:var(--muted);font-size:12px;text-transform:uppercase}.value{font-size:25px;font-weight:700;margin-top:8px}.good{color:var(--green)}.bad{color:var(--red)}.layout{display:grid;grid-template-columns:1.35fr 1fr;gap:16px;margin-top:16px}.wide{grid-column:1/-1}canvas{width:100%;height:260px;background:#0d1527;border-radius:10px}.table-wrap{overflow:auto;max-height:360px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #24314d;text-align:left;white-space:nowrap}th{color:var(--muted);font-size:12px}.insight{border-left:3px solid var(--pink);padding:10px 12px;margin:9px 0;background:#1b2037}.small{color:var(--muted);font-size:12px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}}@media(max-width:560px){.grid{grid-template-columns:1fr}}
</style></head><body><header><img src="logo_bella_stationery.png"><div><h1>Bella Stationery — Profitability Decision Dashboard</h1><div class="by">Prepared by Luciana Gomes Dias Manfredi</div></div></header><main class="wrap"><div class="grid" id="kpis"></div><div class="layout"><section class="panel wide"><h2>Monthly revenue, profit and margin</h2><canvas id="monthly" width="1100" height="280"></canvas></section><section class="panel"><h2>Profitability by sub-category</h2><div class="table-wrap" id="subcat"></div></section><section class="panel"><h2>Profitability by shipping method</h2><div class="table-wrap" id="ship"></div></section><section class="panel"><h2>Decision signals</h2><div id="insights"></div></section><section class="panel"><h2>Data science interpretation</h2><p class="small">Use the tables to prioritize actions, not just sales growth. Negative profit, high shipping share, high discount and return rate are risk signals. Future-dated records after 08 Aug 2026 remain visible and are explicitly flagged in the source analysis.</p><div id="segment"></div></section></div></main><script>const D=__DATA__;const money=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(x);const pct=x=>(100*x).toFixed(1)+'%';
function cards(){let k=D.kpis;let a=[['Revenue',money(k.revenue),''],['Profit',money(k.profit),k.profit<0?'bad':'good'],['Overall margin',pct(k.margin),k.margin<.1?'bad':'good'],['Orders',k.orders.toLocaleString(),''],['Shipping cost',money(k.shipping),''],['Discount value',money(k.discount),''],['Loss-making rows',k.loss_rows.toLocaleString(),'bad'],['Returns',k.returns.toLocaleString(),'']];document.querySelector('#kpis').innerHTML=a.map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value ${x[2]}">${x[1]}</div></div>`).join('')}
function table(el,rows){document.querySelector(el).innerHTML='<table><thead><tr><th>Dimension</th><th>Revenue</th><th>Profit</th><th>Margin</th><th>Return rate</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${r[Object.keys(r)[0]]}</td><td>${money(r.revenue)}</td><td class="${r.profit<0?'bad':'good'}">${money(r.profit)}</td><td>${pct(r.margin||0)}</td><td>${pct(r.return_rate||0)}</td></tr>`).join('')+'</tbody></table>'}
function draw(){let c=document.querySelector('#monthly'),x=c.getContext('2d'),w=c.width,h=c.height,m=42,rows=D.monthly,max=Math.max(...rows.map(r=>r.revenue)),min=Math.min(...rows.map(r=>r.profit)),range=max-min;x.clearRect(0,0,w,h);x.strokeStyle='#263553';x.fillStyle='#9eacc9';x.font='12px system-ui';for(let i=0;i<5;i++){let y=m+i*(h-2*m)/4;x.beginPath();x.moveTo(m,y);x.lineTo(w-m,y);x.stroke();x.fillText(money(max-(max-min)*i/4),4,y+4)}function line(key,color,scaleMin=0,scaleMax=max){x.strokeStyle=color;x.lineWidth=2;x.beginPath();rows.forEach((r,i)=>{let px=m+i*(w-2*m)/(rows.length-1),py=h-m-(r[key]-scaleMin)/(scaleMax-scaleMin)*(h-2*m);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}line('revenue','#5ee7f7',0,max);line('profit','#ff78b6',min,max);x.fillStyle='#5ee7f7';x.fillText('Revenue',w-155,20);x.fillStyle='#ff78b6';x.fillText('Profit',w-85,20)}
function insights(){let sub=D.subcategory, worst=sub[0], best=sub[sub.length-1], ship=D.shipping[0];document.querySelector('#insights').innerHTML=[`<div class="insight"><b>Stop value leakage:</b> ${worst[Object.keys(worst)[0]]} is the weakest sub-category, with ${money(worst.profit)} profit and ${pct(worst.margin||0)} margin.</div>`,`<div class="insight"><b>Scale selectively:</b> ${best[Object.keys(best)[0]]} leads the profitability ranking with ${money(best.profit)} profit.</div>`,`<div class="insight"><b>Logistics review:</b> ${ship[Object.keys(ship)[0]]} is the weakest shipping method in this view; test carrier, service-level and free-shipping thresholds.</div>`,`<div class="insight"><b>Commercial guardrail:</b> investigate transactions combining high discount with negative profit before expanding promotions.</div>`].join('')}
cards();table('#subcat',D.subcategory);table('#ship',D.shipping);table('#segment',D.segment);insights();draw();</script></body></html>'''
(ROOT/'reports/dashboard.html').write_text(html.replace('__DATA__', json.dumps(summary, ensure_ascii=False, default=str)), encoding='utf-8')
print('dashboard generated')
